# Generated by Django 6.0.7 on 2026-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
